# Site settings
title: Daenney
author: Daniele Sluijters
description: Working on the future while maintaining the past.
meta_description: Daenney's blog and ramblings
baseurl: ""
url: "https://daenney.github.io"
github_username:  daenney
twitter_username: daenney

# Build settings
markdown: kramdown
encoding: utf-8
timezone: Etc/UTC
permalink: /:year/:month/:day/:title
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
plugins: [jekyll-paginate]
logo: false
paginate: 10

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "CNAME", "README.md", "vendor"]
