# Site settings
title: Daenney
author: Daniele Sluijters
description: Working on the future while maintaining the past.
meta_description: Daenney's blog and ramblings
baseurl: ""
url: "https://daenney.github.io"
github_username:  daenney
twitter_username: daenney

# Build settings
markdown: kramdown
encoding: utf-8
timezone: Etc/UTC
permalink: /:year/:month/:day/:title
kramdown:
 input: GFM
 hard_wrap: false
 math_engine: mathjax
 syntax_highlighter: rouge
logo: false
paginate: 10
future: true
jailed: false
gfm_quirks: paragraph_end
lsi: false
safe: true
markdown: kramdown
highlighter: rouge
gist:
 noscript: false

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "CNAME", "README.md", "vendor"]
