name: CI

on:
  pull_request: {}
  push:
    branches:
    - master

jobs:
  test:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Build site & validate
      run: |
        bundle exec rake test
    - name: Check Jekyll deprecations
      continue-on-error: true
      run: |
        bundle exec rake doctor
